console_title_template = "{{ .Shell }} in {{ .Folder }}"
final_space = true
version = 3

[[blocks]]
alignment = "left"
type = "prompt"
# [[blocks.segments]]
# background = "#5E81AC"
# foreground = "#ECEFF4"
# leading_diamond = "\ue0b6"
# style = "diamond"
# template = " {{ .UserName }} "
# trailing_diamond = "\ue0b0"
# type = "session"

[[blocks.segments]]
background = "#81A1C1"
foreground = "#ECEFF4"
# powerline_symbol = "\ue0b0"
leading_diamond = "\ue0b6"
trailing_diamond = "\ue0b0"
style = "diamond"
# template = " \uea83  {{ .Path }} "
template = " {{ .Path }} "
type = "path"

[blocks.segments.properties]
folder_separator_icon = " \ue0b1 "
home_icon = "~"
style = "folder"
[[blocks.segments]]
background = "#EBCB8B"
background_templates = [ "{{ if or (.Working.Changed) (.Staging.Changed) }}#D08770{{ end }}", "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#BF616A{{ end }}", "{{ if gt .Ahead 0 }}#B48EAD{{ end }}", "{{ if gt .Behind 0 }}#B48EAD{{ end }}",]
foreground = "#2E3440"
leading_diamond = "\ue0b6"
powerline_symbol = "\ue0b0"
style = "powerline"
template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} "
trailing_diamond = "\ue0b4"
type = "git"

[blocks.segments.properties]
branch_template = "{{ trunc 25 .Branch }}"
fetch_status = true
fetch_upstream_icon = true
[[blocks.segments]]
background = "#A3BE8C"
foreground = "#2E3440"
powerline_symbol = "\ue0b0"
style = "powerline"
template = " \ue718 {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} "
type = "node"

[blocks.segments.properties]
fetch_version = true
[[blocks.segments]]
background = "#88C0D0"
foreground = "#2E3440"
powerline_symbol = "\ue0b0"
style = "powerline"
template = " \ue626 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
type = "go"

[blocks.segments.properties]
fetch_version = true
[[blocks.segments]]
background = "#81A1C1"
foreground = "#2E3440"
powerline_symbol = "\ue0b0"
style = "powerline"
template = " \ue624 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
type = "julia"

[blocks.segments.properties]
fetch_version = true
[[blocks.segments]]
background = "#EBCB8B"
foreground = "#2E3440"
powerline_symbol = "\ue0b0"
style = "powerline"
template = " \ue235 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
type = "python"

[blocks.segments.properties]
display_mode = "files"
fetch_virtual_env = false
[[blocks.segments]]
background = "#BF616A"
foreground = "#ECEFF4"
powerline_symbol = "\ue0b0"
style = "powerline"
template = " \ue791 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
type = "ruby"

[blocks.segments.properties]
display_mode = "files"
fetch_version = true
[[blocks.segments]]
background = "#D08770"
foreground = "#2E3440"
powerline_symbol = "\ue0b0"
style = "powerline"
template = " \uf0e7{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
type = "azfunc"

[blocks.segments.properties]
display_mode = "files"
fetch_version = false
[[blocks.segments]]
background_templates = [ "{{if contains \"default\" .Profile}}#EBCB8B{{end}}", "{{if contains \"jan\" .Profile}}#BF616A{{end}}",]
foreground = "#ECEFF4"
powerline_symbol = "\ue0b0"
style = "powerline"
template = " \ue7ad {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} "
type = "aws"

[blocks.segments.properties]
display_default = false
[[blocks.segments]]
background = "#D8DEE9"
foreground = "#2E3440"
powerline_symbol = "\ue0b0"
style = "powerline"
template = " \uf0ad "
type = "root"

[[blocks.segments]]
background = "#4C566A"
foreground = "#ECEFF4"
style = "plain"
template = "<transparent>\ue0b0</> \ueba2 {{ .FormattedMs }}⠀"
type = "executiontime"

[blocks.segments.properties]
always_enabled = true
[[blocks.segments]]
background = "#8FBCBB"
background_templates = [ "{{ if gt .Code 0 }}#BF616A{{ end }}",]
foreground = "#2E3440"
style = "diamond"
template = "<parentBackground>\ue0b0</> \ue23a "
trailing_diamond = "\ue0b4"
type = "status"

[blocks.segments.properties]
always_enabled = true

[[blocks]]
type = "rprompt"
[[blocks.segments]]
background = "#5E81AC"
foreground = "#ECEFF4"
style = "plain"
template = "<#5E81AC,transparent>\ue0b6</> \uf489 {{ .Name }} <transparent,#5E81AC>\ue0b2</>"
type = "shell"

[[blocks.segments]]
background = "#A3BE8C"
foreground = "#2E3440"
invert_powerline = true
powerline_symbol = "\ue0b2"
style = "powerline"
template = " \uf167 {{ .Icon }}{{ if ne .Status \"stopped\" }}{{ .Artist }} - {{ .Track }}{{ end }} "
type = "ytm"

[blocks.segments.properties]
paused_icon = "\uf04c "
playing_icon = "\uf04b "
[[blocks.segments]]
background = "#BF616A"
background_templates = [ "{{if eq \"Charging\" .State.String}}#88C0D0{{end}}", "{{if eq \"Discharging\" .State.String}}#BF616A{{end}}", "{{if eq \"Full\" .State.String}}#A3BE8C{{end}}",]
foreground = "#ECEFF4"
invert_powerline = true
powerline_symbol = "\ue0b2"
style = "powerline"
template = " {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}\uf295 "
type = "battery"

[blocks.segments.properties]
charged_icon = "\ue22f "
charging_icon = "\ue234 "
discharging_icon = "\ue231 "
[[blocks.segments]]
background = "#4C566A"
foreground = "#ECEFF4"
invert_powerline = true
leading_diamond = "\ue0b2"
style = "diamond"
template = " {{ .CurrentDate | date .Format }} "
trailing_diamond = "\ue0b4"
type = "time"


[transient_prompt]
background = "transparent"
foreground = "#ffffff"
template = "{{ .Shell }}> "
